# To help simplify including Elemental in external projects

ELEM_INC = @CMAKE_INSTALL_PREFIX@/include
ELEM_LIB = @CMAKE_INSTALL_PREFIX@/lib

CC = @CMAKE_C_COMPILER@
CXX = @CMAKE_CXX_COMPILER@
CXX_FLAGS = @CXX_FLAGS@

MATH_LIBS = @MATH_LIBS_STRING@

MPI_CXX_INCLUDE_PATH = @MPI_CXX_INCLUDE_PATH@
MPI_CXX_COMPILE_FLAGS = @MPI_CXX_COMPILE_FLAGS@
MPI_CXX_LINK_FLAGS = @MPI_CXX_LINK_FLAGS@
MPI_CXX_LIBS = @MPI_CXX_LIBS@

ELEM_COMPILE_FLAGS = ${CXX_FLAGS} -I${ELEM_INC} -I${MPI_CXX_INCLUDE_PATH}
ELEM_LINK_FLAGS = -L${ELEM_LIB} ${MPI_CXX_LINK_FLAGS}

HAVE_PMRRR = @HAVE_PMRRR@
ifdef HAVE_PMRRR
  ELEM_LIBS = -lelemental -lplcg -lpmrrr -lcmake-dummy-lib \
              ${MATH_LIBS} ${MPI_CXX_LIBS}
else
  ELEM_LIBS = -lelemental -lplcg -lcmake-dummy-lib \
              ${MATH_LIBS} ${MPI_CXX_LIBS}
endif
