include(ElSetParentScope)

El_set_parent_scope(
  CMAKE_BUILD_TYPE UPPER_BUILD_TYPE CMAKE_CXX_FLAGS_${UPPER_BUILD_TYPE}
  BUILD_SHARED_LIBS
  EL_RELEASE EL_HYBRID EL_SHA1 EL_VERSION_MAJOR EL_VERSION_MINOR
  MPI_C_COMPILER MPI_C_INCLUDE_PATH MPI_C_COMPILE_FLAGS MPI_C_LIBRARIES 
  MPI_CXX_COMPILER MPI_CXX_INCLUDE_PATH MPI_CXX_COMPILE_FLAGS MPI_CXX_LIBRARIES
  EL_LINK_FLAGS
  EL_AVOID_COMPLEX_MPI EL_HAVE_MPI_REDUCE_SCATTER_BLOCK
  EL_REDUCE_SCATTER_BLOCK_VIA_ALLREDUCE EL_USE_BYTE_ALLGATHERS
  MATH_LIBS EL_BLAS_POST EL_LAPACK_POST EL_SCALAPACK_POST EL_HAVE_FLA_BSVD
  EL_HAVE_QUAD EL_HAVE_QUADMATH EL_HAVE_OPENMP EL_HAVE_QT5
  RESTRICT EL_HAVE_F90_INTERFACE)

if(EL_HAVE_QT5)
  El_set_parent_scope(Qt5Widgets_INCLUDE_DIRS Qt5Widgets_DEFINITIONS)
endif()
