# To help simplify including Elemental in external projects

EL_INC = @CMAKE_INSTALL_PREFIX@/include
EL_LIB = @CMAKE_INSTALL_PREFIX@/lib

CC = @CMAKE_C_COMPILER@
CXX = @CMAKE_CXX_COMPILER@

METIS_INC = @METIS_ROOT@/include

EL_LINK_FLAGS = -L${EL_LIB} @MPI_LINK_FLAGS@

ALL_MATH_INC = -I${EL_INC} -I${METIS_INC}
ALL_MATH_LIBS = -lEl -lpmrrr @CMAKE_THREAD_LIBS_INIT@ \
                @MATH_LIBSTRING@ @METIS_LIBSTRING@
ALL_MPI_FLAGS = @MPI_CXX_INCSTRING@ @MPI_CXX_COMPILE_FLAGS@

ifeq (@EL_HAVE_QT5@,TRUE)
  EL_COMPILE_FLAGS = @CXX_FLAGS@ ${ALL_MATH_INC} ${ALL_MPI_FLAGS} \
                     @QT5_COMPILESTRING@ @QT5_INCSTRING@ @QT5_DEFSTRING@
  EL_LIBS = ${ALL_MATH_LIBS} @MPI_CXX_LIBSTRING@ @QT5_LIBSTRING@
else
  EL_COMPILE_FLAGS = @CXX_FLAGS@ ${ALL_MATH_INC} ${ALL_MPI_FLAGS}
  EL_LIBS = ${ALL_MATH_LIBS} @MPI_CXX_LIBSTRING@
endif
